default_context:
  project_name: 'ChaTa-Compare'
  project_slug: 'chata-compare'
  domain_main: 'chata-compare.com'
  domain_staging: 'stag.chata-compare.com'
  docker_swarm_stack_name_main: 'chata-compare-com'
  docker_swarm_stack_name_staging: 'stag-chata-compare-com'
  secret_key: 'acd4efc2d3a48de7e3e2dc7bba1a05fdd30df54338e133bafc06a5364360c760'
  first_superuser: 'admin@chata-compare.com'
  first_superuser_password: 'acd4efc2d3a48de7e3e2dc7bba1a05fdd30df54338e133bafc06a5364360c760'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.chata-compare.com, https://stag.chata-compare.com, https://chata-compare.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@chata-compare.com'
  postgres_password: 'acd4efc2d3a48de7e3e2dc7bba1a05fdd30df54338e133bafc06a5364360c760'
  pgadmin_default_user: 'admin@chata-compare.com'
  pgadmin_default_user_password: 'acd4efc2d3a48de7e3e2dc7bba1a05fdd30df54338e133bafc06a5364360c760'
  traefik_constraint_tag: 'chata-compare.com'
  traefik_constraint_tag_staging: 'stag.chata-compare.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:acd4efc2d3a48de7e3e2dc7bba1a05fdd30df54338e133bafc06a5364360c760'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
