version: '3.3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
      args: 
        env: dev
    command: /start-reload.sh
    environment:
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
    labels:
      - 'traefik.frontend.rule=PathPrefix:/api,/docs,/redoc'
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - traefik.tags=${TRAEFIK_TAG}
      - SERVER_HOST=http://${DOMAIN}
    networks: 
      default: 
        aliases: 
          - ${DOMAIN}
    ports:
      - '8888:80'
    volumes:
      - ./backend/app:/app
      - ./data:/data

  celeryworker:
    build:
      context: ./backend
      dockerfile: celeryworker.dockerfile
      args: 
        env: dev
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
      - SERVER_HOST=http://${DOMAIN}
    volumes:
      - ./backend/app:/app
      - ./data:/data

  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
      args: 
        env: dev
    environment:
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
    volumes:
      - ./backend/app:/app
      - ./data:/data

  frontend:
    build: 
      context: ./frontend
      args: 
        FRONTEND_ENV: dev
    labels:
      - traefik.frontend.rule=PathPrefix:/
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}

  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=DEBUG \
      --accessLog \
      --web
    labels:
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.enable=true
      - traefik.port=80
    ports:
      - '80:80'
      - '8090:8080'

  pgadmin:
    ports:
      - '5050:5050'

  flower:
    ports:
      - '5555:5555'
